version: "3.5"

services:
  db:
    container_name: "db"
    image: "ghcr.io/charleneauger/${DB_IMAGE:-githubactions-mariadb}"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "itsm"
    shm_size: '1gb'
